sudo: required
language: python

python:
  - 2.7

install: 
  - pip install -q coverage
  - pip install -q coveralls
  - pip install -q icalendar
  - pip install -q pytz
  - pip install .

before_script:
  - cd tests

script: make coverage

after_script: coveralls
