sudo: required
language: python

python:
  - 3.9

install:
  - pip install -q coverage
  - pip install -q coveralls
  - pip install .

before_script:
  - cd tests

script: make coverage

after_script: coveralls
